version: '3.8'
services:
  db_test:
    image: postgres:14
    container_name: postgres_db_test
    env_file:
      - .env.test
    environment:
      - TZ=${TZ}
    ports:
      - "${POSTGRES_PORT_TEST}:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  pgdata_test:
